{
 "title": "RP Urban Farm Rack Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rack 1 Stats",
   "type": "timeseries",
   "description": "statistics of all sensors installed on rack 1:\n- CO2\n- Humidity\n- Temperature\n- Light\n- Water\n- Light Power Consumption\n- Water Pump Power Consumption",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "f1 = \r\n  from(bucket: \"CO2\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_co2\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n\r\nf2 = \r\n  from(bucket: \"Humidity\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_humidity\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: float(v: r._value) * 10.0 }))\r\n\r\nf3 = \r\n  from(bucket: \"Temperature\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_temperature\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: float(v: r._value) * 20.0 }))\r\n\r\nf4 = \r\n  from(bucket: \"Light\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_light\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n\r\nf5 = \r\n  from(bucket: \"Water\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_water\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n\r\nf6 = \r\n  from(bucket: \"Power Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rack_1_Light\" or r[\"_measurement\"] == \"Rack_1_Water\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r[\"_measurement\"] == \"Rack_1_Water\" then r._value * 20.0 else r._value\r\n    }))\r\n\r\nunion(tables: [f1, f2, f3, f4, f5, f6])"
    }
   ]
  },
  {
   "title": "Rack 2 Stats",
   "type": "timeseries",
   "description": "statistics of all sensors installed on rack 2:\n- CO2\n- Humidity\n- Temperature\n- Light Power Consumption\n- Water Pump Power Consumption",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "f1 = \r\n  from(bucket: \"CO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack2_co2\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n\r\nf2 = \r\n  from(bucket: \"Humidity\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack2_humidity\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: float(v: r._value) * 10.0 }))\r\n\r\nf3 = \r\n  from(bucket: \"Temperature\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack2_temperature\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: float(v: r._value) * 20.0 }))\r\n\r\nf4 = \r\n  from(bucket: \"Power Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rack_2_Light\" or r[\"_measurement\"] == \"Rack_2_Water\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r[\"_measurement\"] == \"Rack_2_Water\" then r._value * 20.0 else r._value\r\n    }))\r\n\r\nunion(tables: [f1, f2, f3, f4])"
    }
   ]
  },
  {
   "title": "Rack 3 Stats",
   "type": "timeseries",
   "description": "statistics of all sensors installed on rack 3:\n- CO2\n- Humidity\n- Temperature\n- Light Power Consumption\n- Water Pump Power Consumption",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "f1 = \r\n  from(bucket: \"CO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack3_co2\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n\r\nf2 = \r\n  from(bucket: \"Humidity\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack3_humidity\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: float(v: r._value) * 10.0 }))\r\n\r\nf3 = \r\n  from(bucket: \"Power Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rack_3_Light\" or r[\"_measurement\"] == \"Rack_3_Water\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r[\"_measurement\"] == \"Rack_3_Water\" then r._value * 20.0 else r._value\r\n    }))\r\n\r\nunion(tables: [f1, f2, f3])"
    }
   ]
  },
  {
   "title": "Rack 4 Stats",
   "type": "timeseries",
   "description": "statistics of all sensors installed on rack 4:\n- CO2\n- Humidity\n- Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "f1 = \r\n  from(bucket: \"CO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack4_co2\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n\r\nf2 = \r\n  from(bucket: \"Humidity\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack4_humidity\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: float(v: r._value) * 10.0 }))\r\n\r\nf3 = \r\n  from(bucket: \"Temperature\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rack4_temperature\")\r\n    |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: float(v: r._value) * 20.0 }))\r\n\r\nunion(tables: [f1, f2, f3])"
    }
   ]
  },
  {
   "title": "Deployment Layout",
   "type": "text",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<img src=\"https://drive.google.com/uc?id=1eW5JqxND3CJamB7iA0XaRVa_OR1sdAOd\" width=\"65%\" height=\"100%\" style =\"display: block; margin-left: auto; margin-right: auto; margin-top: auto;\"></img>"
   }
  }
 ]
}