{
 "title": "RP Urban Farm Monitoring System",
 "description": "24-Hour Dashboard for RP Farm Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Grow Rack Temperatures",
   "type": "gauge",
   "description": "Most recent temperature readings obtained from growing racks 1 to 4.",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperature\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_temperature\" or r[\"_measurement\"] == \"rack2_temperature\" or r[\"_measurement\"] == \"rack3_temperature\" or r[\"_measurement\"] == \"rack4_temperature\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n       _measurement:\r\n         if r[\"_measurement\"] == \"rack1_temperature\" then \"Rack 1 Temperature\"\r\n         else if r[\"_measurement\"] == \"rack2_temperature\" then \"Rack 2 Temperature\"\r\n         else if r[\"_measurement\"] == \"rack3_temperature\" then \"Rack 3 Temperature\"\r\n         else if r[\"_measurement\"] == \"rack4_temperature\" then \"Rack 4 Temperature\"\r\n         else \"Unknown\",\r\n       _value: r[\"_value\"],\r\n       _time: r[\"_time\"],\r\n       _field: r[\"_field\"]\r\n     }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Grow Rack Humidity Levels",
   "type": "stat",
   "description": "Most recent humidity levels obtained from growing racks 1 to 4.\n",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Humidity\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_humidity\" or r[\"_measurement\"] == \"rack2_humidity\" or r[\"_measurement\"] == \"rack3_humidity\" or r[\"_measurement\"] == \"rack4_humidity\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n       _measurement:\r\n         if r[\"_measurement\"] == \"rack1_humidity\" then \"Rack 1 Humidity\"\r\n         else if r[\"_measurement\"] == \"rack2_humidity\" then \"Rack 2 Humidity\"\r\n         else if r[\"_measurement\"] == \"rack3_humidity\" then \"Rack 3 Humidity\"\r\n         else if r[\"_measurement\"] == \"rack4_humidity\" then \"Rack 4 Humidity\"\r\n         else \"Unknown\",\r\n       _value: r[\"_value\"],\r\n       _time: r[\"_time\"],\r\n       _field: r[\"_field\"]\r\n     }))\r\n"
    }
   ]
  },
  {
   "title": "CO2 Level",
   "type": "stat",
   "description": "Most recent CO2 ppm readings for growing racks 1 to 4.",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_co2\" or r[\"_measurement\"] == \"rack2_co2\" or r[\"_measurement\"] == \"rack3_co2\" or r[\"_measurement\"] == \"rack4_co2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n       _measurement:\r\n         if r[\"_measurement\"] == \"rack1_co2\" then \"Rack 1 CO2\"\r\n         else if r[\"_measurement\"] == \"rack2_co2\" then \"Rack 2 CO2\"\r\n         else if r[\"_measurement\"] == \"rack3_co2\" then \"Rack 3 CO2\"\r\n         else if r[\"_measurement\"] == \"rack4_co2\" then \"Rack 4 CO2\"\r\n         else \"Unknown\",\r\n       _value: r[\"_value\"],\r\n       _time: r[\"_time\"],\r\n       _field: r[\"_field\"]\r\n     }))\r\n"
    }
   ]
  },
  {
   "title": "Grow Light Operational Hours",
   "type": "state-timeline",
   "description": "Grow light operational hours (in green) determined whenever Tuya Sensors have a reading greater than 5 W.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"Power Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rack_1_Light\" or r[\"_measurement\"] == \"Rack_2_Light\" or r[\"_measurement\"] == \"Rack_3_Light\")\r\n  |> aggregateWindow(every: 60m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Water Pump Status",
   "type": "status-history",
   "description": "Water pump status active (blue) determined whenever Tuya Sensors record a reading > 5W.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"Power Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rack_1_Water\" or r[\"_measurement\"] == \"Rack_2_Water\" or r[\"_measurement\"] == \"Rack_3_Water\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Farm Temperature Overview",
   "type": "timeseries",
   "description": "Farm temperature collected using ENVHat Sensors",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperature\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_temperature\" or r[\"_measurement\"] == \"rack2_temperature\" or r[\"_measurement\"] == \"rack3_temperature\" or r[\"_measurement\"] == \"rack4_temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "timeseries",
   "description": "Outdoor Temperature obtained via OpenWeatherMap API",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"WeatherAPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"External Weather Conditions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"temp_max\" or r[\"_field\"] == \"temp_min\" or r[\"_field\"] == \"feels_like\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Farm Humidity Overview",
   "type": "timeseries",
   "description": "Humidity level collected from ENVHat Sensor",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Humidity\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_humidity\" or r[\"_measurement\"] == \"rack2_humidity\" or r[\"_measurement\"] == \"rack3_humidity\" or r[\"_measurement\"] == \"rack4_humidity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Outdoor Humidity Levels",
   "type": "timeseries",
   "description": "Outdoor Humidity collected via OpenWeatherMap API",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"WeatherAPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"External Weather Conditions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Woodlands\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Grow light Power Consumption Overview",
   "type": "timeseries",
   "description": "Power consumption for farm grow lights collected using Tuya Sockets",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"Power Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rack_1_Light\" or r[\"_measurement\"] == \"Rack_2_Light\" or r[\"_measurement\"] == \"Rack_3_Light\")\r\n  |> aggregateWindow(every: 60m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rack 1 Grow Light Intensity",
   "type": "timeseries",
   "description": "Rack 1 grow light intensity",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"Light\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_light\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Water Pump Power Consumption Overview",
   "type": "timeseries",
   "description": "Water Pump Power Consumption Collected using Tuya Sockets",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"Power Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rack_3_Water\" or r[\"_measurement\"] == \"Rack_2_Water\" or r[\"_measurement\"] == \"Rack_1_Water\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Rack 1 Water Flow Rate",
   "type": "timeseries",
   "description": "Rack 1 water flow rate data collected",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"Water\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_water\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Farm CO2 Levels",
   "type": "timeseries",
   "description": "Farm CO2 readings from SGP30 sensors",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"CO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rack1_co2\" or r[\"_measurement\"] == \"rack2_co2\" or r[\"_measurement\"] == \"rack3_co2\" or r[\"_measurement\"] == \"rack4_co2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Outdoor Cloudiness",
   "type": "timeseries",
   "description": "Outdoor cloud conditions retrieved from OpenWeatherMap API",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"WeatherAPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"External Weather Conditions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cloudiness\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Woodlands\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Outdoor Atmospheric Pressure",
   "type": "timeseries",
   "description": "Outdoor atmospheric pressure obtained from OpenWeatherMap API",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"WeatherAPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"External Weather Conditions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_deg\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Woodlands\")\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |"
    }
   ]
  }
 ]
}