version: '3'

services:
  nginx-container:
    image: nginx:latest
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl-certs:/etc/nginx/certs
